// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: todos.sql

package db

import (
	"context"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (title, description, priority, user_id)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateTodoParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Priority    string `json:"priority"`
	UserID      int64  `json:"user_id"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.ExecContext(ctx, createTodo,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.UserID,
	)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = ? AND user_id = ?
`

type DeleteTodoParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one

SELECT id, title, description, priority, complete, user_id FROM todos WHERE id = ? AND user_id = ?
`

type GetTodoByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Return the generated ID
func (q *Queries) GetTodoByID(ctx context.Context, arg GetTodoByIDParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Complete,
		&i.UserID,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, description, priority, complete, user_id FROM todos WHERE user_id = ?
`

func (q *Queries) ListTodos(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Complete,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET title = ?, description = ?, priority = ?, complete = ?, updated_at = NOW()
WHERE id = ? AND user_id = ?
RETURNING id, title, description, priority, complete, user_id
`

type UpdateTodoParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Priority    string `json:"priority"`
	Complete    bool   `json:"complete"`
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Complete,
		arg.ID,
		arg.UserID,
	)
	return err
}
